version: "3.9"
services:
  postgres:
    restart: always
    container_name: db
    image: "postgres:14.4"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mazarope
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    networks:
      - local
    ports:
      - "9020:5432"
volumes:
  postgres_data:
networks:
  local:
    driver: bridge
